#!/bin/sh

# This is a standard run for docker containers.  This invokes the test script

echo "+----------------------+"
echo "|                      |"
echo "| CICD RUN             |"
echo "|                      |"
echo "+----------------------+"
export IMAGE_NAME="$1"
export IMAGE_TAG="cicd-build"
export PARAMETERS="$2"
export CONTAINER_NAME="$(date +"%y%m%d-%H%M%S")-$IMAGE_NAME"

docker run -d --rm --name $CONTAINER_NAME $IMAGE_NAME:$IMAGE_TAG $PARAMETERS &&
./test $CONTAINER_NAME &&
docker stop $CONTAINER_NAME
return $?
